[package]
name = "tauri-plugin-review"
version = "0.1.11"
edition = "2024"
authors = ["Stefan Schick <stefan.schick@stecug.de>"]
repository = "https://github.com/stec-ug-haftungsbeschrankt/tauri-plugin-review"
links = "tauri-plugin-review"

[package.metadata.platforms.support]
windows = { level = "none", notes = "" }
linux = { level = "none", notes = "" }
macos = { level = "none", notes = "" }
android = { level = "full", notes = "" }
ios = { level = "none", notes = "" }

[dependencies]
tauri = "2.9.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
thiserror = "2.0.17"

[build-dependencies]
tauri-plugin = { version = "2.5.2", features = ["build"] }

[lib]
name = "tauri_plugin_review"
crate-type = ["staticlib", "cdylib", "rlib"]
